product-name = "Zeedle"
name = "Zeedle"
version = "0.6.0"
before-packaging-command = "cargo build --release --manifest-path ../Cargo.toml"
formats = ["nsis"]
out-dir = "../target/release"
binaries-dir = "../target/release"
resources = ["DLLs/*.dll"]
authors = ["Jordan Haidee"]
identifier = "dev.zeedle"
copyright = "Copyright © 2025 Zeedle Dev. All rights reserved."

[[binaries]]
path = "Zeedle"
main = true

[nsis]
installer-icon = "../ui/cover.ico"
